#!/bin/python3
import os
from datetime import date

def case():
    # Case
    os.system('clear')
    print("What's the case number?")
    case = input()

    # Case Topic
    os.system('clear')
    print("What was the problem that needed solving?")
    topic = input()

    # Method
    os.system('clear')
    print("""
What did you do to solve this case?
          
Enter the things you did one at a time.
Enter an empty line to continue. 
          """)
    method = []
    while True:
        methodItem = input()
        if methodItem:
            method.append(methodItem)
        else:
            break
    methodText = '\n'.join(method)

    # The things I learned
    os.system('clear')
    print("""
What Did You Learn?

Enter the things you learned one at a time.
Enter an empty line to continue.
    """)
    thingsLearned = []
    while True:
        learnedItem = input()
        if learnedItem:
            thingsLearned.append(learnedItem)
        else:
            break
    learnedText = '\n'.join(thingsLearned)

    # Thoughts
    os.system('clear')
    print("""
Outline any thoughts you had on the process...

Any follow up tasks/thoughts?
What could you do to improve this process?

Enter thoughts one at a time.
Enter an empty line to continue.
    """)
    furtherThoughts = []
    while True:
        thought = input()
        if thought:
            furtherThoughts.append(thought)
        else:
            break
    thoughtText = '\n'.join(furtherThoughts)

    # Name file with current date
    os.system('clear')
    path = '~/logbook/'
    def get_filename_datetime():
        # Use current date to get a text file name.
        return str(date.today()) + "-" + str(topic)+ ".txt"
    name = get_filename_datetime()
    path_to_file = ("/Users/pfleming/logbook/cases/" + name)

    # write info to txt file
    f = open(path_to_file,"a+")
    f.write( str("Case Number: " + case + "\n\n") )
    f.write( str("Problem/Topic:\n" + topic + "\n\n"))
    f.write( str("Method:\n"))
    for methodItem in method:
        f.write( str(methodItem + "\n") )
    f.write(str("\n"))
    f.write( str("What I Learned:\n"))
    for learnedItem in thingsLearned:
        f.write( str(learnedItem + "\n") )
    f.write(str("\n"))
    f.write( str("Further Thoughts:\n"))
    for thought in furtherThoughts:
        f.write( str(thought + "\n") )
    f.write(str("\n"))
    f.close()
    # exit program
    exit()
    

def meeting():
    # Meeting
    os.system('clear')
    print("Who was in the meeting?\n(Enter on one line)\n")
    meeting = input()

    # Topics Discussed
    os.system('clear')
    print("""
What was discussed in this meeting?

Enter topics discussed one at a time.
Enter an empty line to continue.
    """)
    topics = []
    while True:
        topic = input()
        if topic:
            topics.append(topic)
        else:
            break
    topic = '\n'.join(topics)

    # The things I learned
    os.system('clear')
    print("""
What Did You Learn?

Enter the things you learned one at a time.
Enter an empty line to continue.
    """)
    thingsLearned = []
    while True:
        learnedItem = input()
        if learnedItem:
            thingsLearned.append(learnedItem)
        else:
            break
    learnedText = '\n'.join(thingsLearned)

    # Thoughts
    os.system('clear')
    print("""
Outline any thoughts you had from this meeting...

Any follow up tasks/thoughts?
How could you be more effective in future meetings?

Enter thoughts one at a time.
Enter an empty line to continue.
    """)
    furtherThoughts = []
    while True:
        thought = input()
        if thought:
            furtherThoughts.append(thought)
        else:
            break
    thoughtText = '\n'.join(furtherThoughts)

    # Name file with current date
    os.system('clear')
    path = '~/logbook/'
    def get_filename_datetime():
        # Use current date to get a text file name.
        return str(date.today()) + "-Mtng-W-" + str(meeting)+ ".txt"
    name = get_filename_datetime()
    path_to_file = ("/Users/pfleming/logbook/meetings/" + name)

    # write info to txt file
    f = open(path_to_file,"a+")
    f.write( str("Meeting With : " + meeting + "\n\n") )
    f.write( str("Topics Discussed:\n"))
    for topic in topics:
        f.write( str(topic + "\n") )
    f.write(str("\n"))
    f.write( str("What I Learned:\n"))
    for learnedItem in thingsLearned:
        f.write( str(learnedItem + "\n") )
    f.write(str("\n"))
    f.write( str("Further Thoughts:\n"))
    for thought in furtherThoughts:
        f.write( str(thought + "\n") )
    f.write(str("\n"))
    f.close()
    # exit program
    exit()


def coding():
    # Coding Project
    os.system('clear')
    print("Which Project were you working on?\n")
    project = input()

    # Method
    os.system('clear')
    print("""
What did you code/work on?
          
Enter the things you did one at a time.
Enter an empty line to continue. 
          """)
    method = []
    while True:
        methodItem = input()
        if methodItem:
            method.append(methodItem)
        else:
            break
    methodText = '\n'.join(method)

    # The things I learned
    os.system('clear')
    print("""
What Did You Learn?

Enter the things you learned one at a time.
Enter an empty line to continue.
    """)
    thingsLearned = []
    while True:
        learnedItem = input()
        if learnedItem:
            thingsLearned.append(learnedItem)
        else:
            break
    learnedText = '\n'.join(thingsLearned)

    # Thoughts
    os.system('clear')
    print("""
Outline any further thoughts...

Any follow up tasks?
Anything you'd do differnetly in future projects?

Enter thoughts one at a time.
Enter an empty line to continue.
    """)
    furtherThoughts = []
    while True:
        thought = input()
        if thought:
            furtherThoughts.append(thought)
        else:
            break
    thoughtText = '\n'.join(furtherThoughts)

    # Name file with current date
    os.system('clear')
    path = '~/logbook/'
    def get_filename_datetime():
        # Use current date to get a text file name.
        return str(date.today()) + str(project)+ ".txt"
    name = get_filename_datetime()
    path_to_file = ("/Users/pfleming/logbook/coding/" + name)

    # write info to txt file
    f = open(path_to_file,"a+")
    f.write( str("Project: " + project + "\n\n") )
    f.write( str("Work Done:\n"))
    for methodItem in method:
        f.write( str(methodItem + "\n") )
    f.write(str("\n"))
    f.write( str("What I Learned:\n"))
    for learnedItem in thingsLearned:
        f.write( str(learnedItem + "\n") )
    f.write(str("\n"))
    f.write( str("Further Thoughts:\n"))
    for thought in furtherThoughts:
        f.write( str(thought + "\n") )
    f.write(str("\n"))
    f.close()
    # exit program
    exit()



# Entry Selection 
os.system('clear')
print("""
Please choose an entry type:
      
1 - Case
2 - Meeting
3 - Coding
      
      
      """)
while True:
    entrytype = input("Enter selection: ")
    if entrytype == "1":
        case()
    elif entrytype == "2":
        meeting()
    elif entrytype == "3":
        coding()
    else:
        print("\nPlease select a valid number\n")